"Generated by 'django-admin startproject' using Django 1.9.6."

import os
from os.path import dirname, abspath

CONF_DIR = dirname(dirname(abspath(__file__)))
BASE_DIR = dirname(CONF_DIR)
CONF_DIR_NAME = os.path.relpath(CONF_DIR, BASE_DIR)

PROJECT_NAME = 'cf_ldrbrd'
PROJECT_TITLE = 'Codeforces Leaderboard'

SHOW_UNOFFICIAL = True
SHOW_ADD_USERS_PAGE = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = CONF_DIR_NAME + '.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                CONF_DIR_NAME + '.context_processors.settings_processor',
            ],
        },
    },
]

WSGI_APPLICATION = CONF_DIR_NAME + '.wsgi.application'


# Internationalization

LANGUAGE_CODE = 'en-us'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Customize admin site

from django.contrib import admin
admin.site.site_header = PROJECT_TITLE
admin.site.site_title = PROJECT_TITLE


# Static files (CSS, JavaScript, Images)

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

JQUERY_LOCAL_URL = STATIC_URL + 'jquery.js'
JQUERY_CDN_URL = 'https://code.jquery.com/jquery-3.1.1.min.js'
BOOTSTRAP_CSS_LOCAL_URL = STATIC_URL + 'bootstrap.css'
BOOTSTRAP_JS_LOCAL_URL = STATIC_URL + 'bootstrap.js'
BOOTSTRAP_CSS_CDN_URL = 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css'
BOOTSTRAP_JS_CDN_URL = 'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js'

# Import other settings

if "HEROKU" in os.environ:
    from .heroku import *
    print("Using heroku settings")
else:
    try:
        from .local import *
        print("Using local settings")
    except ImportError:
        from .default import *
        print("Using default settings")
